export const ON_CHANGE_TITLE_POST = "ON_CHANGE_TITLE_POST";
export const LOADING_ADD_POST = "LOADING_ADD_POST";
export const ERROR_MESSAGE_ADD_POST = "ERROR_MESSAGE_ADD_POST";
export const SUCCESS_UPLOAD_FILE = "SUCCESS_UPLOAD_FILE";
export const REMOVE_ADD_POST_DATA = "REMOVE_ADD_POST_DATA";
